// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgvtPI7BCuhrqWlbeE0Frzl9wXPPzPnY4',
    appId: '1:540986097814:web:4ef8fe3e5e5716eed982b7',
    messagingSenderId: '540986097814',
    projectId: 'eco-life-f3ea1',
    authDomain: 'eco-life-f3ea1.firebaseapp.com',
    storageBucket: 'eco-life-f3ea1.firebasestorage.app',
    measurementId: 'G-G0BM03C0D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLY5VdzBPpbxC1XzMM3jqV6hwmyTgr3jI',
    appId: '1:540986097814:android:774b5b17f6e2b9edd982b7',
    messagingSenderId: '540986097814',
    projectId: 'eco-life-f3ea1',
    storageBucket: 'eco-life-f3ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu45VQDBzdEbuuz_QqBFIepPfoe7WEyNA',
    appId: '1:540986097814:ios:49d8a81dcf64acafd982b7',
    messagingSenderId: '540986097814',
    projectId: 'eco-life-f3ea1',
    storageBucket: 'eco-life-f3ea1.firebasestorage.app',
    iosBundleId: 'com.example.ecoLife',
  );
}
